name: CI/CD Pipeline Staging

on:
  push:
    branches:
      - staging

env:
  ECR_REPOSITORY_NAME: voltop-landing
  ECR_REPOSITORY: ${{ secrets.VOLTOP_STG_ECR_ID }}/landing

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # - name: Set Doppler Secret
      #   env:
      #     DOPPLER_TOKEN: ${{ secrets.VOLTOP_STAGING_DOPPLER_TOKEN }}
      #   run: |
      #     echo "DOPPLER_TOKEN=$DOPPLER_TOKEN" >> $GITHUB_ENV

      # - uses: dopplerhq/secrets-fetch-action@v1.1.1
      #   id: doppler
      #   with:
      #     doppler-token: ${{ env.DOPPLER_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{env.VOLTOP_STG_AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.VOLTOP_STG_AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.VOLTOP_STG_AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        # env:
          # ENV: ${{ steps.doppler.outputs.ENV }}
          # API_URL: ${{ steps.doppler.outputs.API_URL }}
        run: |
          docker build --rm \
            --tag $ECR_REPOSITORY:prd-${GITHUB_SHA::7} .
          docker push $ECR_REPOSITORY:prd-${GITHUB_SHA::7}

  deploy:
    name: Setup image to k8s repository
    runs-on: ubuntu-latest
    needs: build

    env:
      GITHUB_TOKEN: ${{ secrets.VOLTOP_GITHUB_PAT }}
      K8S_REPOSITORY_MANIFEST: voltop-k8s-manifest
      K8S_ENVIRONMENT: prd
      REPOSITORY_DIR: infra

    steps:
      - name: Check Out Manifest Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.VOLTOP_GITHUB_PAT }}
          repository: ${{ secrets.VOLTOP_GITHUB_ACCOUNT }}/${{ env.K8S_REPOSITORY_MANIFEST }}
          path: ${{ env.REPOSITORY_DIR }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Voltop API Image Tag
        run: |
          cd ${{ env.REPOSITORY_DIR }}/voltop-landing/overlays/${{ env.K8S_ENVIRONMENT }}
          kustomize edit set image ${{ secrets.VOLTOP_STG_ECR_ID }}/voltop-landing=$ECR_REPOSITORY:${{ env.K8S_ENVIRONMENT }}-${GITHUB_SHA::7}

      - name: Commit and Push Changes
        run: |
          cd ${{ env.REPOSITORY_DIR }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Automatically Built in `date +"%Y-%m-%d %H:%M"` From https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          git push

      - name: Print Finish Message
        run: |
          echo "🎉 Sync In Progress.... 🍏 This job's status is ${{ job.status }}."